### ISSUE TITLE
Missing dependency on Test::TempDir::Tiny

### ISSUE THREAD

**Issue by pghmcfc** [dagolden/CPAN-Meta-YAML#3]
YAML-Tiny is bundling this new test requirement, but CPAN-Meta-YAML isn't. Test suite for 0.013 fails on systems that don't have it.

**Comment by dagolden** [comment]
Thanks.  I'll start looking into it.

**Comment by mreeves1** [comment]
I am also running into this during my chef runs that runs `cpanm CPAN::Meta`. Installing CPAN::Meta::YAML 0.012 manually gets me past the issue for the moment. Thanks for looking into this.

**Comment by dagolden** [comment]
CPAN-Meta-YAML 0.014 has shipped to CPAN.  I think it should resolve the issue.  I apologize for the breakage.

**Comment by dagolden** [comment]
I've tested this on a fresh 5.18 and can install CPAN::Meta including CPAN::Meta::YAML (0.014), so I'm going to close this ticket.

**Comment by pghmcfc** [comment]
Just one thing to note: File::Temp introduced newdir() in version 0.19, not version 0.18.

**Comment by dagolden** [comment]
Good catch. I'll fix that upstream.

On Tue, Mar 17, 2015 at 5:06 AM, Paul Howarth <notifications@github.com>
wrote:

> Just one thing to note: File::Temp introduced newdir() in version 0.19,
> not version 0.18.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dagolden/CPAN-Meta-YAML/issues/3#issuecomment-82218749>
> .
>



-- 
David Golden <dagolden@cpan.org> Twitter/IRC: @xdg

**Comment by mreeves1** [comment]
@dagolden It happens! Thanks for your contributions and for fixing this so quickly.
