### ISSUE TITLE
Test dependency on Test::More .99 but not available online

### ISSUE THREAD

**Issue by holybit** [dagolden/CPAN-Meta-YAML#4]
Your depending on a test prereq for Test::More .99 but that version is not currently available on CPAN. I worked around it with a cpanfile that forces a higher version of Test::More but I would say this is a show stopper issue right now.

**Comment by dagolden** [comment]
That version spec means "0.99 or higher".  Why does the availability of that specific version on CPAN matter to you?

In the most general case, I could depend on version "0.12" of module Foo, and the author could be up to version "0.55" and have deleted the "0.12" version off CPAN.

It sounds like you might be doing something wrong with automatic version detection for a cpanfile.

**Comment by holybit** [comment]
Thanks for the reminder on how versioning works. I can't pinpoint the exact issue but upgrading cpamn to latest fixed the problem.

**Comment by dagolden** [comment]
OK, thanks for letting me know!
